{{- $namespaces := index $.Values.cmdArgs "kube.namespaces" }}
{{- $resources := index $.Values.cmdArgs "kube.resources" }}

{{- range $namespace := $namespaces }}
  {{- if and ( not $namespace ) ( gt ( len $namespaces ) 1 )}}
    {{- fail "Can't use several namespaces with all ('') namespaces specified" }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exporter.fullname" . }}
  namespace: {{ include "exporter.fullname" . }}
  labels:
    {{- include "exporter.labels" . | nindent 4 }}
{{- range $namespace := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "ClusterRole" "Role" ( not $namespace ) }}
metadata:
  name: {{ include "exporter.fullname" $ }}
{{ ternary "" ( printf "namespace: %s" $namespace ) ( not $namespace ) | indent 2 }}
  labels:
    {{- include "exporter.labels" $ | nindent 4 }}
rules:
{{- range $resource := $resources }}
  {{- $object :=  include "parse.resource.string" $resource | fromJson }}
  - apiGroups: {{ $object.api | list | toJson }}
    resources: {{ $object.resource | list | toJson }}
    verbs: ["get", "list", "watch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "ClusterRoleBinding" "RoleBinding" ( not $namespace ) }}
metadata:
  name: {{ include "exporter.fullname" $ }}
  namespace: {{ include "exporter.fullname" $ }}
  labels:
    {{- include "exporter.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "exporter.fullname" $ }}
  namespace: {{ include "exporter.fullname" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ ternary "ClusterRole" "Role" ( not $namespace ) }}
  name: {{ include "exporter.fullname" $ }}
{{- end }}
