---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      automountServiceAccountToken: true
      imagePullSecrets:
      - name: registrysecret
      - name: regcred
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.werf.image.app }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ pluck .Values.werf.env .Values.app.args.port | first | default .Values.app.args.port._default }}
          name: metrics
        args:
        - -A={{ pluck .Values.werf.env .Values.app.args.annotations | first | default .Values.app.args.annotations._default | join ","}}
        - -L={{ pluck .Values.werf.env .Values.app.args.labels | first | default .Values.app.args.labels._default | join ","}}
        - -n={{ pluck .Values.werf.env .Values.app.args.namespaces | first | default .Values.app.args.namespaces._default | join "," | quote}}
        - -R={{ pluck .Values.werf.env .Values.app.args.resources | first | default .Values.app.args.resources._default | join ","}}
        - -p={{ pluck .Values.werf.env .Values.app.args.port | first | default .Values.app.args.port._default }}
        - --stats={{ pluck .Values.werf.env .Values.app.args.stats | first | default .Values.app.args.stats._default }}
        command:
        - /annotations-exporter
