---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
 {{- range (pluck .Values.werf.env .Values.app.ports | first | default .Values.app.ports._default) }}
  - port: {{ .port }}
    name: {{ .name }}
 {{- end }}
  selector:
    app: {{ .Chart.Name }}