---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
  - port: {{ pluck .Values.werf.env .Values.app.args.port | first | default .Values.app.args.port._default }}
    name: metrics
  selector:
    app: {{ .Chart.Name }}