app:
  command:
    _default:
    - /annotations-exporter
  args:
    _default:
    - --label=app
    - --annotations=ci.werf.io/commit,gitlab.ci.werf.io/pipeline-url
    - -R deploy,pod,ingress,sts
  ports:
    _default:
    - name: metrics
      port: 5000