app:
  command:
    _default:
    - /annotations-exporter
  args:
    resources:
      _default:
      - sts
      - deploy
      - ingress
      - pod
    annotations:
      _default:
      - ci.werf.io/commit
      - gitlab.ci.werf.io/pipeline-url
    labels:
      _default:
      - app
    namespaces:
      _default:
      - ""  # "" (empty string) for all namespaces
    port:
      _default: 5000
    stats:
      _default: false
